# General Settings
name: Shanty
title: Shanty
job_title: Update Blog
email: ''
description: 'The RSPS with Sea Shanty 2 vibes - we have a reimagined RuneScape world map, the Warding skill, and overall are the most thought-out RuneScape Private Server to exist.'
title_image: /assets/images/logo.png
# avatar: https://example.com/hi.png
favicon: /favicon.ico
twitter_handler: ''
analytics_code: ''
disqus: ''
github_username: 'SeaShantyPS'
rune_server: 'https://www.rune-server.ee/runescape-development/rs2-server/projects/701423-shanty.html#post5763317'

# Social Accounts
social_networks:
- { name: facebook, url: '' }
- { name: twitter, url: '' }
- { name: instagram, url: '' }
- { name: google-plus, url: '' }
- { name: linkedin, url: '' }
- { name: skype, url: '' }
- { name: github, url: '' }
- { name: codepen, url: '' }
- { name: stack-overflow, url: '' }
- { name: dribbble, url: '' }
- { name: behance, url: '' }
- { name: pinterest, url: '' }
- { name: tumblr, url: '' }
- { name: youtube, url: 'https://www.youtube.com/channel/UC-5pzcZgKo2c5Rs4CCe92Bw' }
- { name: vimeo, url: '' }
- { name: vine, url: '' }
- { name: 500px, url: '' }
- { name: flickr, url: '' }
- { name: spotify, url: '' }
- { name: steam, url: '' }
- { name: wordpress, url: '' }
- { name: xing, url: '' }
- { name: bitcoin, url: '' }
- { name: pocket, url: '' }
- { name: applemusic, url: '' }
- { name: reddit, url: 'https://www.reddit.com/user/shantyps' }

# Modules Settings
show_categories: 0
show_tags: 0
show_email: 0
show_rss: 1
show_comments: 1
show_menu: 1
fixed_sidebar: 1
show_rune_server: 1

# Plugins
plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: "https://shanty.ps"

# Includes
include: ["_pages"]

# Outputting
permalink: ":slug"
category_dir: categories

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!-- more -->"

# Assets Settings
sass:
  sass_dir: assets/css
  style: compressed
